{"v":0,"level":30,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T08:02:35.925Z","msg":"Using New Relic for Node.js. Agent version: 2.5.0; Node version: v6.11.2."}
{"v":0,"level":30,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T08:02:36.077Z","msg":"Starting New Relic for Node.js connection process."}
{"v":0,"level":30,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T08:02:42.869Z","msg":"Reporting to: https://rpm.newrelic.com/accounts/1843255/applications/40541962","component":"new_relic_response"}
{"v":0,"level":30,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T08:02:42.870Z","msg":"Connected to collector-234.newrelic.com:443 with agent run ID WzIse2E6NzczODE5NTU3LGI6NDA3NjQ4NjEsYzoxODQzMjU1LGQ6IjIuNS4wIixlOiJub2RlanMiLGY6InBldGVyLmxhbiIsZzpbe2E6NDA1NDE5NjIsYjoiVGVsb3MifV19LDMyOTI5NDA2NDBd.","component":"collector_api"}
{"v":0,"level":50,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T09:59:51.154Z","msg":"Calling metric_data on New Relic failed unexpectedly. Data will be held until it can be submitted:","component":"collector_api","message":"connect ENETUNREACH 50.31.164.145:443 - Local (0.0.0.0:53417)","stack":"Error: connect ENETUNREACH 50.31.164.145:443 - Local (0.0.0.0:53417)\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at connect (net.js:880:16)\n    at net.js:1009:7\n    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)","code":"ENETUNREACH","errno":"ENETUNREACH","syscall":"connect","address":"50.31.164.145","port":443}
{"v":0,"level":30,"name":"newrelic","hostname":"peter.lan","pid":13151,"time":"2018-01-12T09:59:51.156Z","msg":"Error on submission to New Relic (data held for redelivery):","message":"connect ENETUNREACH 50.31.164.145:443 - Local (0.0.0.0:53417)","stack":"Error: connect ENETUNREACH 50.31.164.145:443 - Local (0.0.0.0:53417)\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at connect (net.js:880:16)\n    at net.js:1009:7\n    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)","code":"ENETUNREACH","errno":"ENETUNREACH","syscall":"connect","address":"50.31.164.145","port":443}
